import './jquery-3.6.0.min.js';
import burgers from './../css/header/header.js';
import map from './../css/contacts/map-yandex.js';
import './../css/reviews/swiper-bundle.min.js';
import swiper from './../css/reviews/swiper.js';
import './../css/accordion/jquery-ui.min.js';
import accordion from './../css/accordion/accordion.js';
import modal from './../css/modal/modal.js';
import './../css/form/datepicker/jquery-ui.min.js';
import './../css/form/datepicker/datepicker-ru.js';
import datepicker from './../css/form/datepicker/datepicker.js';
import './../css/form/inputmask.min.js';
import './../css/form/just-validate.production.min.js';
import form from './../css/form/form.js';

burgers();
swiper();
accordion();
map();
modal();
datepicker();
form();